<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\ui_patterns\Definition\PatternDefinition;

/**
 * Implements hook_page_attachments().
 */
function wingsuit_lb_page_attachments(array &$attachments) {
  if (gin_lb_is_layout_builder_route() && gin_lb_is_valid_theme()) {
    $attachments['#attached']['library'][] = 'wingsuit_lb/core';
  }
}

/**
 * Implements hook_ui_patterns_layouts_display_settings_form_alter().
 */
function wingsuit_lb_ui_patterns_layouts_display_settings_form_alter(
  &$form,
  PatternDefinition $definition,
  $configuration
) {
  $form['#type'] = 'container';
  $form['field_templates']['#type'] = 'hidden';
  $form['settings']['#type'] = 'container';
}

/**
 * Implements hook_form_alter().
 */
function wingsuit_lb_form_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id
) {
  if ($form_id === 'node_landing_page_layout_builder_form') {
    hide($form['actions']['submit']);
    $form['actions']['layout_builder_save_and_edit_layout']['#value'] = t(
      'Save'
    );
  }
}

/**
 * Implements hook_preprocess_wingsuit_lb_icon().
 */
function wingsuit_lb_preprocess_wingsuit_lb_icon(&$variables) {
  $uri = $variables['uri'];
  $extension = pathinfo($uri, PATHINFO_EXTENSION);
  if ($extension === 'svg') {
    if (substr($uri, 0,1) === '/') {#
      $uri = substr($uri, 1);
    }
    if (file_exists($uri)) {
      $variables['svg'] = $uri;
    }
  }
}

/**
 * Implements hook_theme().
 */
function wingsuit_lb_theme($existing, $type, $theme, $path) {
  return [

    'wingsuit_lb_icon' => [
      'variables' => [
        'uri' => NULL,
        'width' => NULL,
        'height' => NULL,
        'svg' => NULL,
        'alt' => NULL,
      ],
    ],
  ];
}
