<?php

/**
 * @file
 * Contains important hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wingsuit_companion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wingsuit_companion module.
    case 'help.page.wingsuit_companion':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module add Wingsuit Theme extensions.') . '</p>';
      return $output;

    default:
  }
}
